/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.controller.DiscountController;
import com.mycompany.model.Discount;
import java.time.LocalDateTime;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author hernan
 */
public class Discounts extends javax.swing.JFrame {
private DiscountController discountController;
    /**
     * Creates new form Discounts
     */
    public Discounts() {
        initComponents();
        setLocationRelativeTo(null); 
         // Inicializa el controlador
        discountController = new DiscountController(this, TableDiscounts);
        // Verifica que el controlador esté inicializado correctamente
        System.out.println("discountController inicializado: " + (discountController != null));
        // Actualiza la tabla para mostrar los datos actuales
        discountController.updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        IdShop = new javax.swing.JTextField();
        EventId = new javax.swing.JTextField();
        StartDate = new javax.swing.JTextField();
        ProductId = new javax.swing.JTextField();
        DiscountValue = new javax.swing.JTextField();
        EndDate = new javax.swing.JTextField();
        ComboBoxDiscountType = new javax.swing.JComboBox<>();
        AddDiscount = new javax.swing.JButton();
        EditDiscount = new javax.swing.JButton();
        backk = new javax.swing.JButton();
        SearchDiscountButton = new javax.swing.JButton();
        DeleteDiscount = new javax.swing.JButton();
        SearchDiscount = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDiscounts = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 243, 235));

        jLabel2.setFont(new java.awt.Font("Bradley Hand", 0, 48)); // NOI18N
        jLabel2.setText("Discounts");

        jLabel3.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        jLabel3.setText("Product Id");

        jLabel4.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        jLabel4.setText("Discount Type");

        jLabel5.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        jLabel5.setText("Start Date");

        jLabel6.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        jLabel6.setText("Id shop");

        jLabel7.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        jLabel7.setText("Discount Value");

        jLabel8.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        jLabel8.setText("End Date");

        jLabel9.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        jLabel9.setText("Event Id");

        ComboBoxDiscountType.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N
        ComboBoxDiscountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PERCENTAGE", "FIXED_AMOUNT", "BUNDLE" }));

        AddDiscount.setBackground(new java.awt.Color(232, 224, 194));
        AddDiscount.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N
        AddDiscount.setText("Add Discount");
        AddDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDiscountActionPerformed(evt);
            }
        });

        EditDiscount.setBackground(new java.awt.Color(232, 224, 194));
        EditDiscount.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N
        EditDiscount.setText("Edit Discount");
        EditDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditDiscountActionPerformed(evt);
            }
        });

        backk.setBackground(new java.awt.Color(232, 224, 194));
        backk.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N
        backk.setText("Back");
        backk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backkActionPerformed(evt);
            }
        });

        SearchDiscountButton.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N
        SearchDiscountButton.setText("Search");
        SearchDiscountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchDiscountButtonActionPerformed(evt);
            }
        });

        DeleteDiscount.setBackground(new java.awt.Color(232, 224, 194));
        DeleteDiscount.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N
        DeleteDiscount.setText("Delete Discount");
        DeleteDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteDiscountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(AddDiscount)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DeleteDiscount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditDiscount))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DiscountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ComboBoxDiscountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(IdShop)
                                        .addGap(76, 76, 76))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(SearchDiscountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StartDate)
                    .addComponent(EventId)
                    .addComponent(EndDate)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(backk))
                    .addComponent(SearchDiscount))
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(IdShop, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(EndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(EventId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxDiscountType, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(DiscountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchDiscountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backk, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableDiscounts.setBackground(new java.awt.Color(236, 231, 215));
        TableDiscounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Id Shop", "Product Id", "Discounts Type", "Discount Value", "Start Date", "End Date", "Event Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableDiscounts);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backkActionPerformed
        Others other = new Others();
        other.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backkActionPerformed

    private void SearchDiscountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchDiscountButtonActionPerformed
        try {
        int discountId = Integer.parseInt(SearchDiscount.getText());
        Discount discount = discountController.searchDiscount(discountId);

        if (discount != null) {
            IdShop.setText(String.valueOf(discount.getShopId()));
            ProductId.setText(String.valueOf(discount.getProductId()));
            ComboBoxDiscountType.setSelectedItem(discount.getDiscountType());
            DiscountValue.setText(String.valueOf(discount.getDiscountValue()));
            StartDate.setText(discount.getStartDate().toString());
            EndDate.setText(discount.getEndDate().toString());
            EventId.setText(String.valueOf(discount.getEventId()));
        } else {
            JOptionPane.showMessageDialog(this, "Descuento no encontrado.");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa un ID válido.");
    }
    }//GEN-LAST:event_SearchDiscountButtonActionPerformed

    private void AddDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDiscountActionPerformed
        try {
        int shopId = Integer.parseInt(IdShop.getText());
        int productId = Integer.parseInt(ProductId.getText());
        String discountType = ComboBoxDiscountType.getSelectedItem().toString();
        double discountValue = Double.parseDouble(DiscountValue.getText());
        LocalDateTime startDate = LocalDateTime.parse(StartDate.getText());
        LocalDateTime endDate = LocalDateTime.parse(EndDate.getText());
        int eventId = Integer.parseInt(EventId.getText());

        discountController.createDiscount(shopId, productId, discountType, discountValue, startDate, endDate, eventId);
    } catch (NumberFormatException | DateTimeParseException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa valores válidos.");
    }
    }//GEN-LAST:event_AddDiscountActionPerformed

    private void DeleteDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteDiscountActionPerformed
        try {
        int discountId = Integer.parseInt(SearchDiscount.getText());

        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas eliminar este descuento?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        discountController.deleteDiscount(discountId);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa un ID válido.");
    }
    }//GEN-LAST:event_DeleteDiscountActionPerformed

    private void EditDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDiscountActionPerformed
        try {
        int discountId = Integer.parseInt(SearchDiscount.getText());
        int shopId = Integer.parseInt(IdShop.getText());
        int productId = Integer.parseInt(ProductId.getText());
        String discountType = ComboBoxDiscountType.getSelectedItem().toString();
        double discountValue = Double.parseDouble(DiscountValue.getText());
        LocalDateTime startDate = LocalDateTime.parse(StartDate.getText());
        LocalDateTime endDate = LocalDateTime.parse(EndDate.getText());
        int eventId = Integer.parseInt(EventId.getText());

        Discount discount = new Discount(shopId, productId, discountType, discountValue, startDate, endDate, eventId);
        discountController.updateDiscount(discountId, discount);
    } catch (NumberFormatException | DateTimeParseException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa valores válidos.");
    }
    }//GEN-LAST:event_EditDiscountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Discounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Discounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Discounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Discounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Discounts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDiscount;
    private javax.swing.JComboBox<String> ComboBoxDiscountType;
    private javax.swing.JButton DeleteDiscount;
    private javax.swing.JTextField DiscountValue;
    private javax.swing.JButton EditDiscount;
    private javax.swing.JTextField EndDate;
    private javax.swing.JTextField EventId;
    private javax.swing.JTextField IdShop;
    private javax.swing.JTextField ProductId;
    private javax.swing.JTextField SearchDiscount;
    private javax.swing.JButton SearchDiscountButton;
    private javax.swing.JTextField StartDate;
    private javax.swing.JTable TableDiscounts;
    private javax.swing.JButton backk;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
