/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.controller.PrizeController;
import com.mycompany.model.Prize;
import javax.swing.JOptionPane;

/**
 *
 * @author hernan
 */
public class Prizes extends javax.swing.JFrame {
private PrizeController prizeController;
    /**
     * Creates new form Prizes
     */
    public Prizes() {
        initComponents();
        setLocationRelativeTo(null); 
        prizeController = new PrizeController(this, PrizeTable);
        System.out.println("prizeController inicializado: " + (prizeController != null));
        prizeController.updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PrizeTable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TypePrizeText = new javax.swing.JTextField();
        ParticipantIdText = new javax.swing.JTextField();
        DescriptionPrize = new javax.swing.JTextField();
        ValuePrize = new javax.swing.JTextField();
        ActivityIdText = new javax.swing.JTextField();
        GeneralCategoryText = new javax.swing.JTextField();
        AddPrize = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        SearchPrize = new javax.swing.JButton();
        UpdatePrize = new javax.swing.JButton();
        SearchPrizeText = new javax.swing.JTextField();
        ComboBoxStatus = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 243, 235));

        jLabel1.setFont(new java.awt.Font("Bradley Hand", 0, 48)); // NOI18N
        jLabel1.setText("Who wants a Prize?");

        PrizeTable.setBackground(new java.awt.Color(236, 231, 215));
        PrizeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Type", "Description", "Value", "Status", "Activity Id", "Participant Id", "General Category"
            }
        ));
        jScrollPane1.setViewportView(PrizeTable);

        jLabel15.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        jLabel15.setText("Activity Id");

        jLabel16.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        jLabel16.setText("Type");

        jLabel17.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        jLabel17.setText("General Category");

        jLabel18.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        jLabel18.setText("Description");

        jLabel19.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        jLabel19.setText("Status");

        jLabel20.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        jLabel20.setText("Participant Id");

        jLabel21.setFont(new java.awt.Font("Bradley Hand", 0, 24)); // NOI18N
        jLabel21.setText("Value");

        TypePrizeText.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N

        ParticipantIdText.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N

        DescriptionPrize.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N

        ValuePrize.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N

        ActivityIdText.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N

        GeneralCategoryText.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N

        AddPrize.setBackground(new java.awt.Color(232, 224, 194));
        AddPrize.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N
        AddPrize.setText("Add");
        AddPrize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPrizeActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(232, 224, 194));
        Delete.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        SearchPrize.setBackground(new java.awt.Color(232, 224, 194));
        SearchPrize.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N
        SearchPrize.setText("Search");
        SearchPrize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPrizeActionPerformed(evt);
            }
        });

        UpdatePrize.setBackground(new java.awt.Color(232, 224, 194));
        UpdatePrize.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N
        UpdatePrize.setText("Update");
        UpdatePrize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePrizeActionPerformed(evt);
            }
        });

        SearchPrizeText.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N

        ComboBoxStatus.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N
        ComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AVAILABLE", "DELIVERED" }));

        jButton1.setBackground(new java.awt.Color(232, 224, 194));
        jButton1.setFont(new java.awt.Font("Bradley Hand", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(256, 256, 256))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(AddPrize)
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ActivityIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ParticipantIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GeneralCategoryText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(140, 140, 140))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Delete)
                                .addGap(81, 81, 81)
                                .addComponent(UpdatePrize)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(40, 40, 40))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DescriptionPrize, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TypePrizeText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel19))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ValuePrize)
                                    .addComponent(ComboBoxStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(121, 121, 121)
                        .addComponent(SearchPrize)
                        .addGap(18, 18, 18)
                        .addComponent(SearchPrizeText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel17)
                            .addComponent(GeneralCategoryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValuePrize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(TypePrizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ActivityIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(ParticipantIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DescriptionPrize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(SearchPrize)
                            .addComponent(SearchPrizeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddPrize)
                    .addComponent(Delete)
                    .addComponent(UpdatePrize)
                    .addComponent(jButton1))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddPrizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPrizeActionPerformed
        try {
            String type = TypePrizeText.getText();
            String description = DescriptionPrize.getText();
            double value = Double.parseDouble(ValuePrize.getText());
            String status = ComboBoxStatus.getSelectedItem().toString();
            int activityId = Integer.parseInt(ActivityIdText.getText());
            int participantId = Integer.parseInt(ParticipantIdText.getText());
            int generalCategoryId = Integer.parseInt(GeneralCategoryText.getText());

            prizeController.createPrize(type, description, value, status, activityId, participantId, generalCategoryId);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa valores válidos.");
        }
    }//GEN-LAST:event_AddPrizeActionPerformed

    private void UpdatePrizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePrizeActionPerformed
        try {
            int prizeId = Integer.parseInt(SearchPrizeText.getText());
            String type = TypePrizeText.getText();
            String description = DescriptionPrize.getText();
            double value = Double.parseDouble(ValuePrize.getText());
            String status = ComboBoxStatus.getSelectedItem().toString();
            int activityId = Integer.parseInt(ActivityIdText.getText());
            int participantId = Integer.parseInt(ParticipantIdText.getText());
            int generalCategoryId = Integer.parseInt(GeneralCategoryText.getText());

            Prize prize = new Prize(type, description, value, status, activityId, participantId, generalCategoryId);
            prizeController.updatePrize(prizeId, prize);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa valores válidos.");
        }
    }//GEN-LAST:event_UpdatePrizeActionPerformed

    private void SearchPrizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPrizeActionPerformed
        try {
            int prizeId = Integer.parseInt(SearchPrizeText.getText());
            Prize prize = prizeController.searchPrize(prizeId);

            if (prize != null) {
                TypePrizeText.setText(prize.getType());
                DescriptionPrize.setText(prize.getDescription());
                ValuePrize.setText(String.valueOf(prize.getValue()));
                ComboBoxStatus.setSelectedItem(prize.getStatus());
                ActivityIdText.setText(String.valueOf(prize.getActivityId()));
                ParticipantIdText.setText(String.valueOf(prize.getParticipantId()));
                GeneralCategoryText.setText(String.valueOf(prize.getGeneralCategoryId()));
            } else {
                JOptionPane.showMessageDialog(this, "Premio no encontrado.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un ID válido.");
        }
    }//GEN-LAST:event_SearchPrizeActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        try {
            int prizeId = Integer.parseInt(SearchPrizeText.getText());

            int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas eliminar este premio?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            prizeController.deletePrize(prizeId);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa un ID válido.");
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Others other = new Others();
        other.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prizes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prizes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prizes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prizes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prizes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ActivityIdText;
    private javax.swing.JButton AddPrize;
    private javax.swing.JComboBox<String> ComboBoxStatus;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField DescriptionPrize;
    private javax.swing.JTextField GeneralCategoryText;
    private javax.swing.JTextField ParticipantIdText;
    private javax.swing.JTable PrizeTable;
    private javax.swing.JButton SearchPrize;
    private javax.swing.JTextField SearchPrizeText;
    private javax.swing.JTextField TypePrizeText;
    private javax.swing.JButton UpdatePrize;
    private javax.swing.JTextField ValuePrize;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
